server:
  port: 8010

spring:
  application:
    name: ConfigClientDemo

foo: bar_git_Default

# ----------------------------------
spring:
  profiles: DEV
  
test: test_git_DEV
# ----------------------------------
